In [1]:
import numpy as np

In [4]:
x = np.arange(25).reshape(5, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Boolean indexing

In [3]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
print(x[(x<=7) & (x>3)])

[4 5 6 7]


### Atribuição de valores

In [8]:
x[x<7] = 1
x

array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Operações de conjuntos

In [9]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

In [10]:
# interseção
np.intersect1d(x,y)

array([2, 4])

In [11]:
# união
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
# x - y
np.setdiff1d(x,y)

array([1, 3, 5])

# Sort


### Uma dimensão

In [19]:
x = np.random.randint(1,11,size=(10,))
x

array([ 8,  7,  9,  7, 10,  7,  3,  3, 10,  9])

In [20]:
np.sort(x)

array([ 3,  3,  7,  7,  7,  8,  9,  9, 10, 10])

In [21]:
x

array([ 8,  7,  9,  7, 10,  7,  3,  3, 10,  9])

In [23]:
np.sort(np.unique(x))

array([ 3,  7,  8,  9, 10])

### Mais dimensões

In [24]:
y = np.random.randint(1,11,size=(5,5))
y

array([[3, 6, 6, 9, 6],
       [9, 7, 4, 3, 5],
       [7, 5, 6, 5, 2],
       [9, 4, 5, 8, 7],
       [7, 3, 7, 8, 2]])

In [25]:
np.sort(y, axis = 0)

array([[3, 3, 4, 3, 2],
       [7, 4, 5, 5, 2],
       [7, 5, 6, 8, 5],
       [9, 6, 6, 8, 6],
       [9, 7, 7, 9, 7]])

In [26]:
np.sort(y, axis = 1)

array([[3, 6, 6, 6, 9],
       [3, 4, 5, 7, 9],
       [2, 5, 5, 6, 7],
       [4, 5, 7, 8, 9],
       [2, 3, 7, 7, 8]])