In [2]:
import numpy as np

## Formas de dividir o array

1. ndarray[inicio:fim]
2. ndarray[inicio:]
3. ndarray[:fim]


Em 2, o início é inclusivo. Em 1 e em 3, o fim é exclusivo.

In [3]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 1

In [13]:
 x[0:3, 1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

## 2

In [11]:
x[1: ,1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

## 3

In [12]:
x[:3, :3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

## Pegando certa coluna

In [15]:
x[:, 2]

array([ 2,  7, 12, 17])

## Pegando certa linha

In [16]:
x[2, :]

array([10, 11, 12, 13, 14])

## Pegando uma coluna sem deformá-la

Mantém o rank numpy igual a 2.

In [19]:
x[:, 2:3]

array([[ 2],
       [ 7],
       [12],
       [17]])

# OLHA A BAGUNÇA

Esse comportamento do numpy é muito, mas muito doido.

In [22]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
z = x[1:, 2:]
z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [26]:
z[2,2] = 1001

# WHAT???????????

Alterar o objeto z alterou x. Isso é simplesmente surreal.

In [27]:
x

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18, 1001]])

## Função para resolver a lambança

In [31]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
z = x[1:, 2:].copy()

In [33]:
z[2, 2] = 1001

In [35]:
z

array([[   7,    8,    9],
       [  12,   13,   14],
       [  17,   18, 1001]])

In [37]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Usar um array como índices para selecionar elementos de outro array


In [38]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
indices = np.array([1,3])
indices

array([1, 3])

In [45]:
y = x[indices, :]
y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [47]:
y = x[:, indices]
y

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

# Funções de seleção mais específicas

## Diagonal

In [49]:
# diagonal principal
z = np.diag(x)
z

array([ 0,  6, 12, 18])

In [50]:
# uma diagonal acima da principal
z = np.diag(x, k = 1)
z

array([ 1,  7, 13, 19])

In [52]:
# uma diagonal abaixo da principal
z = np.diag(x, k = -1)
z

array([ 5, 11, 17])

## Elementos únicos

In [55]:
x = np.array([[1,2,3],[5,2,8],[1,2,3]])
z = np.unique(x)
z

array([1, 2, 3, 5, 8])