# Numpy

In [ ]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [4]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Exibindo tipos contidos no array

In [7]:
x.dtype


dtype('int32')

In [8]:
x.shape

(5,)

In [9]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

2

In [10]:
Y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
Y.shape

(4, 3)

In [13]:
Y.size

12

In [20]:
x = np.array([1, 2])
print(x)

[1 2]


In [21]:
print('x = ', x)
print('x.shape:', x.shape)
print('x é do tipo:', type(x))
print('Os elementos de x são do tipo:', x.dtype)

x =  [1 2]
x.shape: (2,)
x é do tipo: <class 'numpy.ndarray'>
Os elementos de x são do tipo: int32


### Upcasting

In [22]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


### Escolhendo um dtype para o ndarray

Parece typecasting

In [23]:
x = np.array([1.5, 2.2, 3.7], dtype =np.int64)
print(x)
print('dtype', x.dtype)

[1 2 3]
dtype int64


### Salvando arrays em arquivos

In [25]:
x = np.array([1, 2 , 3, 4 , 5])
np.save('hello_world', x)

### Carregando array salvo

In [29]:
y = np.load('hello_world.npy')
print(y)

[1 2 3 4 5]


## Criando matriz preenchida por zeros ou outros valores

In [34]:
x = np.zeros((3,4), dtype=int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
x.dtype

dtype('int32')

In [37]:
x = np.ones((4,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
x = np.full((4, 3), 5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [41]:
print(x.dtype)

int32


## Matriz identidade

In [44]:
# matriz 5x5
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Matriz diagonal

In [46]:
x = np.diag([10, 20, 30 , 50])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


### Arange

Parece o seq() do R, só mudam os índices: $[0, n)$ -> (é inclusivo para $n-1$).

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [63]:
np.arange(4, 12 ,2)

array([ 4,  6,  8, 10])

## Linspace

É parecido com o Arange, mas dessa vez os argumentos são inclusivos e o terceiro argumento não define o tamanho dos saltos até chegar ao fim do intervalo, mas sim a **QUANTIDADE DE NÚMEROS NO ARRAY**.

In [64]:
np.linspace(1, 27, 30)

array([ 1.        ,  1.89655172,  2.79310345,  3.68965517,  4.5862069 ,
        5.48275862,  6.37931034,  7.27586207,  8.17241379,  9.06896552,
        9.96551724, 10.86206897, 11.75862069, 12.65517241, 13.55172414,
       14.44827586, 15.34482759, 16.24137931, 17.13793103, 18.03448276,
       18.93103448, 19.82758621, 20.72413793, 21.62068966, 22.51724138,
       23.4137931 , 24.31034483, 25.20689655, 26.10344828, 27.        ])

In [65]:
# Torna o limite superior exclusivo
np.linspace(1, 27, 30, endpoint = False)

array([ 1.        ,  1.86666667,  2.73333333,  3.6       ,  4.46666667,
        5.33333333,  6.2       ,  7.06666667,  7.93333333,  8.8       ,
        9.66666667, 10.53333333, 11.4       , 12.26666667, 13.13333333,
       14.        , 14.86666667, 15.73333333, 16.6       , 17.46666667,
       18.33333333, 19.2       , 20.06666667, 20.93333333, 21.8       ,
       22.66666667, 23.53333333, 24.4       , 25.26666667, 26.13333333])

## Reshape

In [68]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
np.reshape(x, (4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
np.reshape(x, (10,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

## Atributos em sequência

In [75]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [77]:
x = np.linspace(0, 50, 10, endpoint = False).reshape(5, 2)
x

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

## Matrizes aleatórias

In [82]:
np.random.random((3,3))

array([[0.56057769, 0.39277675, 0.52818719],
       [0.2307129 , 0.15239122, 0.63680512],
       [0.71902037, 0.96195586, 0.12645269]])

In [83]:
# gera um número entre 4 e 15 e cria uma matriz 3x2
np.random.randint(4, 15, (3 ,2))

array([[14, 11],
       [ 8, 13],
       [ 6, 12]])

In [87]:
# matriz 1000x1000 gerada com números gerados por uma distribuição normal
mean = 0
sd = 1
np.random.normal(mean, sd, size = (1000, 1000))

array([[ 0.18628616, -0.99152081, -0.52554228, ...,  0.79776742,
         0.61898687,  0.71135414],
       [-1.21050018,  0.11070921,  1.58410354, ..., -0.23618434,
         1.78253124,  0.94122528],
       [ 0.08604134,  0.38960871,  1.26624468, ..., -0.60994274,
        -0.04787989,  1.73991742],
       ...,
       [-0.17202326,  0.28858325,  0.14247889, ..., -0.49929987,
        -0.49097855,  0.85242002],
       [ 0.37903247,  0.51559274,  0.83589803, ...,  1.08804302,
         0.0717481 , -0.18127898],
       [-0.66169397,  0.39347003, -0.90342456, ...,  0.503123  ,
         1.1591222 ,  0.35294164]])

In [89]:
X = np.random.normal(mean, sd, size = (1000, 1000))
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -0.00056634173849589
The maximum value in X is: 5.277697476627419
The minimum value in X is: -4.761068936796548
X has 500335 negative numbers
X has 499665 positive numbers
