In [4]:
import numpy as np

In [5]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

In [6]:
print(x+y)
print(np.add(x,y))

[ 6.5  8.5 10.5 12.5]
[ 6.5  8.5 10.5 12.5]


In [8]:
print(x - y)
print(np.subtract(x,y))

[-4.5 -4.5 -4.5 -4.5]
[-4.5 -4.5 -4.5 -4.5]


In [13]:
x = np.array([1,2,3,4]).reshape(2,2)
print("x:{}".format(x))
y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print("y:{}".format(y))

x:[[1 2]
 [3 4]]
y:[[5.5 6.5]
 [7.5 8.5]]


In [14]:
x/y

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [15]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [16]:
np.exp(y)

array([[ 244.69193226,  665.14163304],
       [1808.04241446, 4914.7688403 ]])

In [17]:
np.power(x, 2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [19]:
x.mean()

2.5

In [23]:
x.std()

1.118033988749895

In [24]:
# média das linhas
x.mean(axis= 1)

array([1.5, 3.5])

In [25]:
# média das colunas
x.mean(axis= 0)

array([2., 3.])

## Broadcasting

In [27]:
x / 3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

In [28]:
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
x = np.arange(3)
x

array([0, 1, 2])

In [31]:
print(y + x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [32]:
z = np.arange(3).reshape(3, 1)
z

array([[0],
       [1],
       [2]])

In [34]:
z + y

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])